package com.southsouthwest.framelog.ui.settings

import android.app.Application
import android.content.Context
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.southsouthwest.framelog.data.AppPreferences
import com.southsouthwest.framelog.data.AppTheme
import com.southsouthwest.framelog.data.ExportFormat
import com.southsouthwest.framelog.data.GpsPrecision
import com.southsouthwest.framelog.data.db.AppDatabase
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.receiveAsFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.io.File

// ---------------------------------------------------------------------------
// UiState
// ---------------------------------------------------------------------------

data class SettingsUiState(
    // Shooting defaults
    val extraFramesPerRoll: Int = 2,
    val gpsPrecision: GpsPrecision = GpsPrecision.HIGH,
    val defaultExportFormat: ExportFormat = ExportFormat.CSV,
    // Appearance
    val appTheme: AppTheme = AppTheme.SYSTEM,
    val accessibleColorMode: Boolean = false,
    // In-progress operations
    val isExportingBackup: Boolean = false,
    val isRestoringBackup: Boolean = false,
)

// ---------------------------------------------------------------------------
// Events
// ---------------------------------------------------------------------------

sealed class SettingsEvent {
    /**
     * The database backup file is ready to share.
     * The UI creates an Intent with this URI for the Android share sheet.
     * [filePath] is the path to the temporary copy of the database file.
     */
    data class ShareBackupFile(val filePath: String) : SettingsEvent()
    /**
     * Restore completed — the app must restart to use the restored database.
     * The UI should prompt the user to restart.
     */
    data object RestoreCompleteRestartRequired : SettingsEvent()
    /** Show the tip jar link in a web browser or in-app browser. */
    data object OpenTipJar : SettingsEvent()
    /** Navigate to the OSS licenses screen (generated by the Play OSS Licenses plugin). */
    data object OpenOssLicenses : SettingsEvent()
    /** Re-run the onboarding coach marks. Navigate to the Welcome screen. */
    data object NavigateToOnboarding : SettingsEvent()
    /** Navigate to Widget Setup Instructions screen. */
    data object NavigateToWidgetSetup : SettingsEvent()
    data class ShowErrorMessage(val message: String) : SettingsEvent()
    data class ShowInfoMessage(val message: String) : SettingsEvent()
}

// ---------------------------------------------------------------------------
// ViewModel
// ---------------------------------------------------------------------------

class SettingsViewModel(application: Application) : AndroidViewModel(application) {

    private val appPreferences = AppPreferences(application)

    private val _state = MutableStateFlow(
        SettingsUiState(
            extraFramesPerRoll = appPreferences.extraFramesPerRoll,
            gpsPrecision = appPreferences.gpsPrecision,
            defaultExportFormat = appPreferences.defaultExportFormat,
            appTheme = appPreferences.appTheme,
            accessibleColorMode = appPreferences.accessibleColorMode,
        )
    )
    val state: StateFlow<SettingsUiState> = _state.asStateFlow()

    private val _events = Channel<SettingsEvent>(Channel.BUFFERED)
    val events: Flow<SettingsEvent> = _events.receiveAsFlow()

    // ---------------------------------------------------------------------------
    // Shooting defaults
    // ---------------------------------------------------------------------------

    fun onExtraFramesChanged(count: Int) {
        val clamped = count.coerceIn(0, 10)
        appPreferences.extraFramesPerRoll = clamped
        _state.update { it.copy(extraFramesPerRoll = clamped) }
    }

    fun onGpsPrecisionChanged(precision: GpsPrecision) {
        appPreferences.gpsPrecision = precision
        _state.update { it.copy(gpsPrecision = precision) }
    }

    fun onDefaultExportFormatChanged(format: ExportFormat) {
        appPreferences.defaultExportFormat = format
        _state.update { it.copy(defaultExportFormat = format) }
    }

    // ---------------------------------------------------------------------------
    // Appearance
    // ---------------------------------------------------------------------------

    fun onAppThemeChanged(theme: AppTheme) {
        appPreferences.appTheme = theme
        _state.update { it.copy(appTheme = theme) }
    }

    fun onAccessibleColorModeChanged(enabled: Boolean) {
        appPreferences.accessibleColorMode = enabled
        _state.update { it.copy(accessibleColorMode = enabled) }
    }

    // ---------------------------------------------------------------------------
    // Data & Backup
    // ---------------------------------------------------------------------------

    /**
     * Copies the Room database file to the app's cache directory and emits
     * [SettingsEvent.ShareBackupFile] so the UI can create a share Intent.
     *
     * Room keeps up to three files for a database (db, db-wal, db-shm). The WAL file
     * contains un-checkpointed writes. To produce a consistent snapshot we force a
     * WAL checkpoint before copying.
     */
    fun onExportBackupTapped() = viewModelScope.launch {
        _state.update { it.copy(isExportingBackup = true) }
        try {
            val app = getApplication<Application>()
            val backupPath = withContext(Dispatchers.IO) {
                createBackupFile(app)
            }
            _events.send(SettingsEvent.ShareBackupFile(backupPath))
        } catch (e: Exception) {
            _events.send(SettingsEvent.ShowErrorMessage("Backup failed: ${e.message}"))
        } finally {
            _state.update { it.copy(isExportingBackup = false) }
        }
    }

    /**
     * Replaces the current database with a user-provided backup file.
     *
     * [backupFilePath] is the path to the .framelog file selected by the user via
     * the system file picker. This operation is destructive — all current data is
     * overwritten. The caller must have shown a danger confirmation before invoking.
     *
     * Room must be closed before the file is replaced. After the copy the app must
     * restart for Room to pick up the new database.
     */
    fun onRestoreBackupConfirmed(backupFilePath: String) = viewModelScope.launch {
        _state.update { it.copy(isRestoringBackup = true) }
        try {
            val app = getApplication<Application>()
            withContext(Dispatchers.IO) {
                restoreFromBackup(app, backupFilePath)
            }
            _events.send(SettingsEvent.RestoreCompleteRestartRequired)
        } catch (e: Exception) {
            _events.send(SettingsEvent.ShowErrorMessage("Restore failed: ${e.message}"))
        } finally {
            _state.update { it.copy(isRestoringBackup = false) }
        }
    }

    // ---------------------------------------------------------------------------
    // Navigation shortcuts
    // ---------------------------------------------------------------------------

    fun onRerunOnboardingTapped() = viewModelScope.launch {
        appPreferences.onboardingComplete = false
        _events.send(SettingsEvent.NavigateToOnboarding)
    }

    fun onWidgetSetupTapped() = viewModelScope.launch {
        _events.send(SettingsEvent.NavigateToWidgetSetup)
    }

    fun onTipJarTapped() = viewModelScope.launch {
        _events.send(SettingsEvent.OpenTipJar)
    }

    fun onOssLicensesTapped() = viewModelScope.launch {
        _events.send(SettingsEvent.OpenOssLicenses)
    }

    // ---------------------------------------------------------------------------
    // Backup file I/O
    // ---------------------------------------------------------------------------

    /**
     * Creates a consistent backup by checkpointing the WAL then copying the database file.
     * Returns the absolute path of the backup file in the cache directory.
     */
    private fun createBackupFile(context: Context): String {
        // Room database files live in getDatabasePath()
        val dbFile = context.getDatabasePath("framelog.db")

        // Force WAL checkpoint so all writes are in the main db file, not the WAL.
        // We do this by opening a SQLite connection and running PRAGMA wal_checkpoint.
        android.database.sqlite.SQLiteDatabase.openDatabase(
            dbFile.absolutePath,
            null,
            android.database.sqlite.SQLiteDatabase.OPEN_READWRITE,
        ).use { db ->
            db.execSQL("PRAGMA wal_checkpoint(TRUNCATE)")
        }

        // Copy the main database file to the cache dir as a .framelog file
        val cacheDir = context.cacheDir
        val timestamp = System.currentTimeMillis()
        val backupFile = File(cacheDir, "framelog_backup_$timestamp.framelog")
        dbFile.copyTo(backupFile, overwrite = true)
        return backupFile.absolutePath
    }

    /**
     * Replaces the current database file with the backup.
     * Room must be closed before this runs — called from the ViewModel which
     * holds no Room connection itself, but the Repository/AppDatabase singleton
     * must be closed by the caller or handled at the Application level.
     *
     * NOTE: In practice the app process must restart after restore. The UI emits
     * [SettingsEvent.RestoreCompleteRestartRequired] and the Activity calls
     * ProcessPhoenix or recreate() to restart cleanly.
     */
    private fun restoreFromBackup(context: Context, backupFilePath: String) {
        val backupFile = File(backupFilePath)
        require(backupFile.exists()) { "Backup file not found: $backupFilePath" }

        val dbFile = context.getDatabasePath("framelog.db")

        // Close the Room singleton before overwriting the file
        AppDatabase.closeInstance()

        backupFile.copyTo(dbFile, overwrite = true)

        // Also remove WAL and SHM files if present to avoid stale state
        File("${dbFile.absolutePath}-wal").delete()
        File("${dbFile.absolutePath}-shm").delete()
    }
}
