package com.southsouthwest.framelog.ui.settings

import android.app.Application
import android.content.Context
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.southsouthwest.framelog.data.AppPreferences
import com.southsouthwest.framelog.data.AppTheme
import com.southsouthwest.framelog.data.ExportFormat
import com.southsouthwest.framelog.data.db.AppDatabase
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.receiveAsFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.io.File

// ---------------------------------------------------------------------------
// UiState
// ---------------------------------------------------------------------------

data class SettingsUiState(
    // Shooting defaults
    val extraFramesPerRoll: Int = 2,
    val gpsCaptureEnabled: Boolean = false,
    val defaultExportFormat: ExportFormat = ExportFormat.CSV,
    val shutterSoundEnabled: Boolean = true,
    // Appearance
    val appTheme: AppTheme = AppTheme.SYSTEM,
    val accessibleColorMode: Boolean = false,
    val apertureWheelReversed: Boolean = false,
    // In-progress operations
    val isExportingBackup: Boolean = false,
    val isRestoringBackup: Boolean = false,
)

// ---------------------------------------------------------------------------
// Events
// ---------------------------------------------------------------------------

sealed class SettingsEvent {
    /**
     * The database backup file is ready to share.
     * The UI creates an Intent with this URI for the Android share sheet.
     * [filePath] is the path to the temporary copy of the database file.
     */
    data class ShareBackupFile(val filePath: String) : SettingsEvent()
    /**
     * Restore completed — the app must restart to use the restored database.
     * The UI should prompt the user to restart.
     */
    data object RestoreCompleteRestartRequired : SettingsEvent()
    /** Navigate to the OSS licenses screen (generated by the Play OSS Licenses plugin). */
    data object OpenOssLicenses : SettingsEvent()
    /** Re-run the onboarding coach marks. Navigate to the Welcome screen. */
    data object NavigateToOnboarding : SettingsEvent()
    /** Navigate to Widget Setup Instructions screen. */
    data object NavigateToWidgetSetup : SettingsEvent()
    /** Database reset completed — the app must restart to initialise a fresh database. */
    data object ResetCompleteRestartRequired : SettingsEvent()
    data class ShowErrorMessage(val message: String) : SettingsEvent()
    data class ShowInfoMessage(val message: String) : SettingsEvent()
}

// ---------------------------------------------------------------------------
// ViewModel
// ---------------------------------------------------------------------------

class SettingsViewModel(application: Application) : AndroidViewModel(application) {

    private val appPreferences = AppPreferences(application)

    private val _state = MutableStateFlow(
        SettingsUiState(
            extraFramesPerRoll = appPreferences.extraFramesPerRoll,
            gpsCaptureEnabled = appPreferences.gpsCaptureEnabled,
            defaultExportFormat = appPreferences.defaultExportFormat,
            shutterSoundEnabled = appPreferences.shutterSoundEnabled,
            appTheme = appPreferences.appTheme,
            accessibleColorMode = appPreferences.accessibleColorMode,
            apertureWheelReversed = appPreferences.apertureWheelReversed,
        )
    )
    val state: StateFlow<SettingsUiState> = _state.asStateFlow()

    private val _events = Channel<SettingsEvent>(Channel.BUFFERED)
    val events: Flow<SettingsEvent> = _events.receiveAsFlow()

    // ---------------------------------------------------------------------------
    // Shooting defaults
    // ---------------------------------------------------------------------------

    fun onExtraFramesChanged(count: Int) {
        val clamped = count.coerceIn(0, 10)
        appPreferences.extraFramesPerRoll = clamped
        _state.update { it.copy(extraFramesPerRoll = clamped) }
    }

    fun onGpsCaptureEnabledChanged(enabled: Boolean) {
        appPreferences.gpsCaptureEnabled = enabled
        _state.update { it.copy(gpsCaptureEnabled = enabled) }
    }

    fun onDefaultExportFormatChanged(format: ExportFormat) {
        appPreferences.defaultExportFormat = format
        _state.update { it.copy(defaultExportFormat = format) }
    }

    fun onShutterSoundEnabledChanged(enabled: Boolean) {
        appPreferences.shutterSoundEnabled = enabled
        _state.update { it.copy(shutterSoundEnabled = enabled) }
    }

    // ---------------------------------------------------------------------------
    // Appearance
    // ---------------------------------------------------------------------------

    fun onAppThemeChanged(theme: AppTheme) {
        appPreferences.appTheme = theme
        _state.update { it.copy(appTheme = theme) }
    }

    fun onAccessibleColorModeChanged(enabled: Boolean) {
        appPreferences.accessibleColorMode = enabled
        _state.update { it.copy(accessibleColorMode = enabled) }
    }

    fun onApertureWheelReversedChanged(reversed: Boolean) {
        appPreferences.apertureWheelReversed = reversed
        _state.update { it.copy(apertureWheelReversed = reversed) }
    }

    // ---------------------------------------------------------------------------
    // Data & Backup
    // ---------------------------------------------------------------------------

    /**
     * Copies the Room database file to the app's cache directory and emits
     * [SettingsEvent.ShareBackupFile] so the UI can create a share Intent.
     *
     * Room keeps up to three files for a database (db, db-wal, db-shm). The WAL file
     * contains un-checkpointed writes. To produce a consistent snapshot we force a
     * WAL checkpoint before copying.
     */
    fun onExportBackupTapped() = viewModelScope.launch {
        _state.update { it.copy(isExportingBackup = true) }
        try {
            val app = getApplication<Application>()
            val backupPath = withContext(Dispatchers.IO) {
                createBackupFile(app)
            }
            _events.send(SettingsEvent.ShareBackupFile(backupPath))
        } catch (e: Exception) {
            _events.send(SettingsEvent.ShowErrorMessage("Backup failed: ${e.message}"))
        } finally {
            _state.update { it.copy(isExportingBackup = false) }
        }
    }

    /**
     * Replaces the current database with a user-provided backup file.
     *
     * [backupFilePath] is the path to the .detent file selected by the user via
     * the system file picker. This operation is destructive — all current data is
     * overwritten. The caller must have shown a danger confirmation before invoking.
     *
     * Room must be closed before the file is replaced. After the copy the app must
     * restart for Room to pick up the new database.
     */
    fun onRestoreBackupConfirmed(backupFilePath: String) = viewModelScope.launch {
        _state.update { it.copy(isRestoringBackup = true) }
        try {
            val app = getApplication<Application>()
            withContext(Dispatchers.IO) {
                restoreFromBackup(app, backupFilePath)
            }
            _events.send(SettingsEvent.RestoreCompleteRestartRequired)
        } catch (e: Exception) {
            _events.send(SettingsEvent.ShowErrorMessage("Restore failed: ${e.message}"))
        } finally {
            _state.update { it.copy(isRestoringBackup = false) }
        }
    }

    /**
     * Wipes the entire Room database by deleting all three database files.
     * SharedPreferences (settings, active roll ID, onboarding flag) are untouched.
     *
     * Room must be closed before the files are deleted. After deletion Room will
     * create a fresh empty database on next access, so the app must restart.
     */
    fun onResetDatabaseConfirmed() = viewModelScope.launch {
        try {
            val app = getApplication<Application>()
            withContext(Dispatchers.IO) {
                resetDatabase(app)
            }
            _events.send(SettingsEvent.ResetCompleteRestartRequired)
        } catch (e: Exception) {
            _events.send(SettingsEvent.ShowErrorMessage("Reset failed: ${e.message}"))
        }
    }

    // ---------------------------------------------------------------------------
    // Navigation shortcuts
    // ---------------------------------------------------------------------------

    fun onRerunOnboardingTapped() = viewModelScope.launch {
        appPreferences.onboardingComplete = false
        _events.send(SettingsEvent.NavigateToOnboarding)
    }

    fun onWidgetSetupTapped() = viewModelScope.launch {
        _events.send(SettingsEvent.NavigateToWidgetSetup)
    }

    fun onOssLicensesTapped() = viewModelScope.launch {
        _events.send(SettingsEvent.OpenOssLicenses)
    }

    // ---------------------------------------------------------------------------
    // Backup file I/O
    // ---------------------------------------------------------------------------

    /**
     * Creates a consistent backup by closing Room then copying the database file.
     * Returns the absolute path of the backup file in the cache directory.
     *
     * Why close instead of checkpoint:
     * WAL checkpoint (TRUNCATE/FULL) requires exclusive access — Room's connection pool
     * keeps at least one reader alive, so the checkpoint may leave frames un-checkpointed
     * in the WAL file even after the PRAGMA returns. Copying only the main db file then
     * produces an incomplete snapshot (missing any writes still in the WAL).
     *
     * Closing Room via [AppDatabase.closeInstance] causes SQLite to perform an automatic
     * full WAL checkpoint before the last connection is released, guaranteeing the main
     * db file is a complete, consistent snapshot. Room reopens lazily on next access.
     */
    private fun createBackupFile(context: Context): String {
        val dbFile = context.getDatabasePath("detent.db")

        // Close Room — SQLite checkpoints the WAL automatically when the last connection closes.
        AppDatabase.closeInstance()

        // Copy the main database file to the cache dir as a .detent file
        val cacheDir = context.cacheDir
        val timestamp = System.currentTimeMillis()
        val backupFile = File(cacheDir, "detent_backup_$timestamp.detent")
        dbFile.copyTo(backupFile, overwrite = true)
        return backupFile.absolutePath
    }

    /**
     * Replaces the current database file with the backup.
     * Room must be closed before this runs — called from the ViewModel which
     * holds no Room connection itself, but the Repository/AppDatabase singleton
     * must be closed by the caller or handled at the Application level.
     *
     * NOTE: In practice the app process must restart after restore. The UI emits
     * [SettingsEvent.RestoreCompleteRestartRequired] and the Activity calls
     * ProcessPhoenix or recreate() to restart cleanly.
     */
    private fun restoreFromBackup(context: Context, backupFilePath: String) {
        val backupFile = File(backupFilePath)
        require(backupFile.exists()) { "Backup file not found: $backupFilePath" }

        val dbFile = context.getDatabasePath("detent.db")

        // Close the Room singleton before overwriting the file
        AppDatabase.closeInstance()

        backupFile.copyTo(dbFile, overwrite = true)

        // Also remove WAL and SHM files if present to avoid stale state
        File("${dbFile.absolutePath}-wal").delete()
        File("${dbFile.absolutePath}-shm").delete()
    }

    /**
     * Deletes all three Room database files, producing a clean slate.
     * SharedPreferences are not touched.
     *
     * Room reopens lazily on next access and creates a fresh empty database.
     * The app must restart so that all in-memory state (active roll ID, etc.)
     * is re-evaluated against the now-empty database.
     */
    private fun resetDatabase(context: Context) {
        val dbFile = context.getDatabasePath("detent.db")

        // Close the Room singleton before deleting — same pattern as backup/restore
        AppDatabase.closeInstance()

        dbFile.delete()
        File("${dbFile.absolutePath}-wal").delete()
        File("${dbFile.absolutePath}-shm").delete()
    }
}
